logging:
    level:
        web: DEBUG

spring:
    profiles.active: local
    data:
        mongodb:
            uri: mongodb+srv://set.with.mongodb.com

zengine:
    story:
        folder: /stories
